"""add picture to users

Revision ID: 005d5a4d70f9
Revises: '1ce66eb41058'
Create Date: 2026-08-07 21:56:29.808231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '005d5a4d70f9'
down_revision: Union[str, None] = '1ce66eb41058'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None




def upgrade() -> None:

    target_type_enum = postgresql.ENUM(
    'PIN',
    'QUESTION',
    'REPLY',
    'COURSE',
    'USER',
    'TOPIC',
    name='targettype',
    create_type=False
       )

    difficulty_enum = sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficultylevel')
    difficulty_enum.create(op.get_bind(), checkfirst=True)

    question_type_enum = sa.Enum('MULTIPLE_CHOICE', 'TRUE_FALSE', 'OPEN_ENDED', name='questiontype')
    question_type_enum.create(op.get_bind(), checkfirst=True)



    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('follower_id', sa.Uuid(), nullable=False),
    sa.Column('target_type', target_type_enum, nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_follows_created_at'), 'follows', ['created_at'], unique=False)
    op.create_index(op.f('ix_follows_follower_id'), 'follows', ['follower_id'], unique=False)
    op.create_index(op.f('ix_follows_id'), 'follows', ['id'], unique=False)
    op.create_index(op.f('ix_follows_target_id'), 'follows', ['target_id'], unique=False)
    op.create_index(op.f('ix_follows_target_type'), 'follows', ['target_type'], unique=False)
    op.create_table('recent_study_items',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('item_type', sa.Enum('COURSE', 'DOCUMENT', 'PAST_EXAM', name='studyitemtype'), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('subtitle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('continue_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('last_opened_at', sa.DateTime(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recent_study_items_created_at'), 'recent_study_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_recent_study_items_id'), 'recent_study_items', ['id'], unique=False)
    op.create_index(op.f('ix_recent_study_items_item_id'), 'recent_study_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_recent_study_items_item_type'), 'recent_study_items', ['item_type'], unique=False)
    op.create_index(op.f('ix_recent_study_items_last_opened_at'), 'recent_study_items', ['last_opened_at'], unique=False)
    op.create_index(op.f('ix_recent_study_items_user_id'), 'recent_study_items', ['user_id'], unique=False)
    op.create_table('user_activities',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('activity_type', sa.Enum('CREATED_PIN', 'ASKED_QUESTION', 'REPLIED_TO_QUESTION', 'ACCEPTED_ANSWER', 'EARNED_BADGE', 'COMPLETED_COURSE', name='activitytype'), nullable=False),
    sa.Column('target_type', target_type_enum, nullable=True),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_activities_activity_type'), 'user_activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_user_activities_created_at'), 'user_activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_activities_id'), 'user_activities', ['id'], unique=False)
    op.create_index(op.f('ix_user_activities_target_id'), 'user_activities', ['target_id'], unique=False)
    op.create_index(op.f('ix_user_activities_target_type'), 'user_activities', ['target_type'], unique=False)
    op.create_index(op.f('ix_user_activities_user_id'), 'user_activities', ['user_id'], unique=False)
    op.create_table('topics',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('normalized_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_course_id'), 'topics', ['course_id'], unique=False)
    op.create_index(op.f('ix_topics_created_at'), 'topics', ['created_at'], unique=False)
    op.create_index(op.f('ix_topics_id'), 'topics', ['id'], unique=False)
    op.create_index(op.f('ix_topics_normalized_name'), 'topics', ['normalized_name'], unique=False)
    op.create_table('topic_analytics',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_analytics_course_id'), 'topic_analytics', ['course_id'], unique=False)
    op.create_index(op.f('ix_topic_analytics_created_at'), 'topic_analytics', ['created_at'], unique=False)
    op.create_index(op.f('ix_topic_analytics_id'), 'topic_analytics', ['id'], unique=False)
    op.create_index(op.f('ix_topic_analytics_topic_id'), 'topic_analytics', ['topic_id'], unique=True)
    op.create_table('topic_year_analytics',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_year_analytics_academic_year'), 'topic_year_analytics', ['academic_year'], unique=False)
    op.create_index(op.f('ix_topic_year_analytics_created_at'), 'topic_year_analytics', ['created_at'], unique=False)
    op.create_index(op.f('ix_topic_year_analytics_id'), 'topic_year_analytics', ['id'], unique=False)
    op.create_index(op.f('ix_topic_year_analytics_topic_id'), 'topic_year_analytics', ['topic_id'], unique=False)
    op.drop_index(op.f('ix_refresh_tokens_created_at'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('playing_with_neon')
    op.alter_column('choices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('choices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index(op.f('ix_choices_created_at'), 'choices', ['created_at'], unique=False)
    op.drop_constraint(op.f('choices_question_id_fkey'), 'choices', type_='foreignkey')
    op.create_foreign_key(None, 'choices', 'questions', ['question_id'], ['id'])
    op.alter_column('content_blocks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('content_blocks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_index(op.f('ix_content_blocks_content_tsv_gin'), table_name='content_blocks', postgresql_using='gin')
    op.create_index(op.f('ix_content_blocks_created_at'), 'content_blocks', ['created_at'], unique=False)
    op.drop_constraint(op.f('content_blocks_document_id_fkey'), 'content_blocks', type_='foreignkey')
    op.create_foreign_key(None, 'content_blocks', 'documents', ['document_id'], ['id'])
    op.add_column('courses', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('courses', sa.Column('visibility', sa.Enum('PUBLIC', 'FOLLOWERS_ONLY', 'PRIVATE', name='visibility'), nullable=False))
    op.alter_column('courses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('courses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index(op.f('ix_courses_category'), 'courses', ['category'], unique=False)
    op.create_index(op.f('ix_courses_created_at'), 'courses', ['created_at'], unique=False)
    op.create_index(op.f('ix_courses_visibility'), 'courses', ['visibility'], unique=False)
    op.drop_constraint(op.f('courses_created_by_user_id_fkey'), 'courses', type_='foreignkey')
    op.create_foreign_key(None, 'courses', 'users', ['created_by_user_id'], ['id'])
    op.alter_column('document_processing_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('document_processing_jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index(op.f('ix_document_processing_jobs_created_at'), 'document_processing_jobs', ['created_at'], unique=False)
    op.drop_constraint(op.f('document_processing_jobs_document_id_fkey'), 'document_processing_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'document_processing_jobs', 'documents', ['document_id'], ['id'])
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index(op.f('ix_documents_created_at'), 'documents', ['created_at'], unique=False)
    op.drop_constraint(op.f('documents_uploaded_by_user_id_fkey'), 'documents', type_='foreignkey')
    op.drop_constraint(op.f('documents_course_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'users', ['uploaded_by_user_id'], ['id'])
    op.create_foreign_key(None, 'documents', 'courses', ['course_id'], ['id'])
    op.alter_column('embeddings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('embeddings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index(op.f('ix_embeddings_created_at'), 'embeddings', ['created_at'], unique=False)
    op.drop_constraint(op.f('embeddings_content_block_id_fkey'), 'embeddings', type_='foreignkey')
    op.create_foreign_key(None, 'embeddings', 'content_blocks', ['content_block_id'], ['id'])
    op.alter_column('exams', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('exams', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index(op.f('ix_exams_created_at'), 'exams', ['created_at'], unique=False)
    op.drop_constraint(op.f('exams_document_id_fkey'), 'exams', type_='foreignkey')
    op.create_foreign_key(None, 'exams', 'documents', ['document_id'], ['id'])
    op.alter_column('knowledge_pins', 'location_metadata_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.create_index(op.f('ix_knowledge_pins_selection_end_offset'), 'knowledge_pins', ['selection_end_offset'], unique=False)
    op.create_index(op.f('ix_knowledge_pins_selection_start_offset'), 'knowledge_pins', ['selection_start_offset'], unique=False)
    op.drop_constraint(op.f('knowledge_pins_author_id_fkey'), 'knowledge_pins', type_='foreignkey')
    op.drop_constraint(op.f('knowledge_pins_document_id_fkey'), 'knowledge_pins', type_='foreignkey')
    op.create_foreign_key(None, 'knowledge_pins', 'users', ['author_id'], ['id'])
    op.create_foreign_key(None, 'knowledge_pins', 'documents', ['document_id'], ['id'])
    op.alter_column('learning_questions', 'location_metadata_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.create_index(op.f('ix_learning_questions_selection_end_offset'), 'learning_questions', ['selection_end_offset'], unique=False)
    op.create_index(op.f('ix_learning_questions_selection_start_offset'), 'learning_questions', ['selection_start_offset'], unique=False)
    op.drop_constraint(op.f('learning_questions_author_id_fkey'), 'learning_questions', type_='foreignkey')
    op.drop_constraint(op.f('learning_questions_document_id_fkey'), 'learning_questions', type_='foreignkey')
    op.create_foreign_key(None, 'learning_questions', 'users', ['author_id'], ['id'])
    op.create_foreign_key(None, 'learning_questions', 'documents', ['document_id'], ['id'])
    op.alter_column('question_content_block_links', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('question_content_block_links', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index(op.f('ix_question_content_block_links_created_at'), 'question_content_block_links', ['created_at'], unique=False)
    op.drop_constraint(op.f('question_content_block_links_question_id_fkey'), 'question_content_block_links', type_='foreignkey')
    op.drop_constraint(op.f('question_content_block_links_content_block_id_fkey'), 'question_content_block_links', type_='foreignkey')
    op.create_foreign_key(None, 'question_content_block_links', 'questions', ['question_id'], ['id'])
    op.create_foreign_key(None, 'question_content_block_links', 'content_blocks', ['content_block_id'], ['id'])
    op.alter_column('question_replies', 'edit_history_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.drop_constraint(op.f('question_replies_question_id_fkey'), 'question_replies', type_='foreignkey')
    op.drop_constraint(op.f('question_replies_parent_reply_id_fkey'), 'question_replies', type_='foreignkey')
    op.drop_constraint(op.f('question_replies_author_id_fkey'), 'question_replies', type_='foreignkey')
    op.create_foreign_key(None, 'question_replies', 'question_replies', ['parent_reply_id'], ['id'])
    op.create_foreign_key(None, 'question_replies', 'users', ['author_id'], ['id'])
    op.create_foreign_key(None, 'question_replies', 'learning_questions', ['question_id'], ['id'])
    op.add_column('questions', sa.Column('topic_id', sa.Uuid(), nullable=True))
    op.add_column('questions', sa.Column('subtopic', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('questions', sa.Column('difficulty', difficulty_enum, nullable=True))
    op.add_column('questions', sa.Column('question_type', question_type_enum, nullable=True))
    op.add_column('questions', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('questions', sa.Column('page_number', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('location_json', sa.JSON(), nullable=True))
    op.alter_column('questions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('questions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index(op.f('ix_questions_created_at'), 'questions', ['created_at'], unique=False)
    op.create_index(op.f('ix_questions_page_number'), 'questions', ['page_number'], unique=False)
    op.create_index(op.f('ix_questions_topic_id'), 'questions', ['topic_id'], unique=False)
    op.drop_constraint(op.f('questions_exam_id_fkey'), 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'exams', ['exam_id'], ['id'])
    op.create_foreign_key(None, 'questions', 'topics', ['topic_id'], ['id'])
    op.drop_constraint(op.f('uq_reactions_user_target_type_id'), 'reactions', type_='unique')
    op.create_index(op.f('ix_reactions_created_at'), 'reactions', ['created_at'], unique=False)
    op.drop_constraint(op.f('reactions_user_id_fkey'), 'reactions', type_='foreignkey')
    op.create_foreign_key(None, 'reactions', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('uq_saved_items_user_target'), 'saved_items', type_='unique')
    op.create_index(op.f('ix_saved_items_created_at'), 'saved_items', ['created_at'], unique=False)
    op.drop_constraint(op.f('saved_items_user_id_fkey'), 'saved_items', type_='foreignkey')
    op.create_foreign_key(None, 'saved_items', 'users', ['user_id'], ['id'])
    op.alter_column('student_answers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('student_answers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index(op.f('ix_student_answers_created_at'), 'student_answers', ['created_at'], unique=False)
    op.drop_constraint(op.f('student_answers_student_id_fkey'), 'student_answers', type_='foreignkey')
    op.drop_constraint(op.f('student_answers_question_id_fkey'), 'student_answers', type_='foreignkey')
    op.drop_constraint(op.f('student_answers_selected_choice_id_fkey'), 'student_answers', type_='foreignkey')
    op.create_foreign_key(None, 'student_answers', 'users', ['student_id'], ['id'])
    op.create_foreign_key(None, 'student_answers', 'questions', ['question_id'], ['id'])
    op.create_foreign_key(None, 'student_answers', 'choices', ['selected_choice_id'], ['id'])
    op.add_column('users', sa.Column('picture',sa.String(), nullable=True))
    op.add_column('users', sa.Column('auth0_id',sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.create_index(op.f('ix_users_auth0_id'), 'users', ['auth0_id'], unique=True)
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', postgresql.ENUM('STUDENT', 'INSTRUCTOR', 'ADMIN', name='userrole'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_auth0_id'), table_name='users')
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'auth0_id')
    op.drop_column('users', 'picture')
    op.drop_constraint(None, 'student_answers', type_='foreignkey')
    op.drop_constraint(None, 'student_answers', type_='foreignkey')
    op.drop_constraint(None, 'student_answers', type_='foreignkey')
    op.create_foreign_key(op.f('student_answers_selected_choice_id_fkey'), 'student_answers', 'choices', ['selected_choice_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('student_answers_question_id_fkey'), 'student_answers', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('student_answers_student_id_fkey'), 'student_answers', 'users', ['student_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_student_answers_created_at'), table_name='student_answers')
    op.alter_column('student_answers', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('student_answers', 'created_at',
               existing_typquestiontypeeTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_constraint(None, 'saved_items', type_='foreignkey')
    op.create_foreign_key(op.f('saved_items_user_id_fkey'), 'saved_items', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_saved_items_created_at'), table_name='saved_items')
    op.create_unique_constraint(op.f('uq_saved_items_user_target'), 'saved_items', ['user_id', 'target_type', 'target_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'reactions', type_='foreignkey')
    op.create_foreign_key(op.f('reactions_user_id_fkey'), 'reactions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_reactions_created_at'), table_name='reactions')
    op.create_unique_constraint(op.f('uq_reactions_user_target_type_id'), 'reactions', ['user_id', 'target_type', 'target_id', 'reaction_type'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key(op.f('questions_exam_id_fkey'), 'questions', 'exams', ['exam_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_questions_topic_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_page_number'), table_name='questions')
    op.drop_index(op.f('ix_questions_created_at'), table_name='questions')
    op.alter_column('questions', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('questions', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_column('questions', 'location_json')
    op.drop_column('questions', 'page_number')
    op.drop_column('questions', 'confidence')
    op.drop_column('questions', 'question_type')
    op.drop_column('questions', 'difficulty')
    op.drop_column('questions', 'subtopic')
    op.drop_column('questions', 'topic_id')
    op.drop_constraint(None, 'question_replies', type_='foreignkey')
    op.drop_constraint(None, 'question_replies', type_='foreignkey')
    op.drop_constraint(None, 'question_replies', type_='foreignkey')
    op.create_foreign_key(op.f('question_replies_author_id_fkey'), 'question_replies', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('question_replies_parent_reply_id_fkey'), 'question_replies', 'question_replies', ['parent_reply_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('question_replies_question_id_fkey'), 'question_replies', 'learning_questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.alter_column('question_replies', 'edit_history_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.drop_constraint(None, 'question_content_block_links', type_='foreignkey')
    op.drop_constraint(None, 'question_content_block_links', type_='foreignkey')
    op.create_foreign_key(op.f('question_content_block_links_content_block_id_fkey'), 'question_content_block_links', 'content_blocks', ['content_block_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('question_content_block_links_question_id_fkey'), 'question_content_block_links', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_question_content_block_links_created_at'), table_name='question_content_block_links')
    op.alter_column('question_content_block_links', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('question_content_block_links', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_constraint(None, 'learning_questions', type_='foreignkey')
    op.drop_constraint(None, 'learning_questions', type_='foreignkey')
    op.create_foreign_key(op.f('learning_questions_document_id_fkey'), 'learning_questions', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('learning_questions_author_id_fkey'), 'learning_questions', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_learning_questions_selection_start_offset'), table_name='learning_questions')
    op.drop_index(op.f('ix_learning_questions_selection_end_offset'), table_name='learning_questions')
    op.alter_column('learning_questions', 'location_metadata_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.drop_constraint(None, 'knowledge_pins', type_='foreignkey')
    op.drop_constraint(None, 'knowledge_pins', type_='foreignkey')
    op.create_foreign_key(op.f('knowledge_pins_document_id_fkey'), 'knowledge_pins', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('knowledge_pins_author_id_fkey'), 'knowledge_pins', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_knowledge_pins_selection_start_offset'), table_name='knowledge_pins')
    op.drop_index(op.f('ix_knowledge_pins_selection_end_offset'), table_name='knowledge_pins')
    op.alter_column('knowledge_pins', 'location_metadata_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.drop_constraint(None, 'exams', type_='foreignkey')
    op.create_foreign_key(op.f('exams_document_id_fkey'), 'exams', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_exams_created_at'), table_name='exams')
    op.alter_column('exams', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('exams', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_constraint(None, 'embeddings', type_='foreignkey')
    op.create_foreign_key(op.f('embeddings_content_block_id_fkey'), 'embeddings', 'content_blocks', ['content_block_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_embeddings_created_at'), table_name='embeddings')
    op.alter_column('embeddings', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('embeddings', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_course_id_fkey'), 'documents', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('documents_uploaded_by_user_id_fkey'), 'documents', 'users', ['uploaded_by_user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_documents_created_at'), table_name='documents')
    op.alter_column('documents', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('documents', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_constraint(None, 'document_processing_jobs', type_='foreignkey')
    op.create_foreign_key(op.f('document_processing_jobs_document_id_fkey'), 'document_processing_jobs', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_document_processing_jobs_created_at'), table_name='document_processing_jobs')
    op.alter_column('document_processing_jobs', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('document_processing_jobs', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.create_foreign_key(op.f('courses_created_by_user_id_fkey'), 'courses', 'users', ['created_by_user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_courses_visibility'), table_name='courses')
    op.drop_index(op.f('ix_courses_created_at'), table_name='courses')
    op.drop_index(op.f('ix_courses_category'), table_name='courses')
    op.alter_column('courses', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('courses', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_column('courses', 'visibility')
    op.drop_column('courses', 'category')
    op.drop_constraint(None, 'content_blocks', type_='foreignkey')
    op.create_foreign_key(op.f('content_blocks_document_id_fkey'), 'content_blocks', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_content_blocks_created_at'), table_name='content_blocks')
    op.create_index(op.f('ix_content_blocks_content_tsv_gin'), 'content_blocks', ['content_tsv'], unique=False, postgresql_using='gin')
    op.alter_column('content_blocks', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('content_blocks', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_constraint(None, 'choices', type_='foreignkey')
    op.create_foreign_key(op.f('choices_question_id_fkey'), 'choices', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_choices_created_at'), table_name='choices')
    op.alter_column('choices', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('choices', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('playing_with_neon_pkey'))
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('revoked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('refresh_tokens_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('refresh_tokens_pkey'))
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_created_at'), 'refresh_tokens', ['created_at'], unique=False)
    op.drop_index(op.f('ix_topic_year_analytics_topic_id'), table_name='topic_year_analytics')
    op.drop_index(op.f('ix_topic_year_analytics_id'), table_name='topic_year_analytics')
    op.drop_index(op.f('ix_topic_year_analytics_created_at'), table_name='topic_year_analytics')
    op.drop_index(op.f('ix_topic_year_analytics_academic_year'), table_name='topic_year_analytics')
    op.drop_table('topic_year_analytics')
    op.drop_index(op.f('ix_topic_analytics_topic_id'), table_name='topic_analytics')
    op.drop_index(op.f('ix_topic_analytics_id'), table_name='topic_analytics')
    op.drop_index(op.f('ix_topic_analytics_created_at'), table_name='topic_analytics')
    op.drop_index(op.f('ix_topic_analytics_course_id'), table_name='topic_analytics')
    op.drop_table('topic_analytics')
    op.drop_index(op.f('ix_topics_normalized_name'), table_name='topics')
    op.drop_index(op.f('ix_topics_id'), table_name='topics')
    op.drop_index(op.f('ix_topics_created_at'), table_name='topics')
    op.drop_index(op.f('ix_topics_course_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_user_activities_user_id'), table_name='user_activities')
    op.drop_index(op.f('ix_user_activities_target_type'), table_name='user_activities')
    op.drop_index(op.f('ix_user_activities_target_id'), table_name='user_activities')
    op.drop_index(op.f('ix_user_activities_id'), table_name='user_activities')
    op.drop_index(op.f('ix_user_activities_created_at'), table_name='user_activities')
    op.drop_index(op.f('ix_user_activities_activity_type'), table_name='user_activities')
    op.drop_table('user_activities')
    op.drop_index(op.f('ix_recent_study_items_user_id'), table_name='recent_study_items')
    op.drop_index(op.f('ix_recent_study_items_last_opened_at'), table_name='recent_study_items')
    op.drop_index(op.f('ix_recent_study_items_item_type'), table_name='recent_study_items')
    op.drop_index(op.f('ix_recent_study_items_item_id'), table_name='recent_study_items')
    op.drop_index(op.f('ix_recent_study_items_id'), table_name='recent_study_items')
    op.drop_index(op.f('ix_recent_study_items_created_at'), table_name='recent_study_items')
    op.drop_table('recent_study_items')
    op.drop_index(op.f('ix_follows_target_type'), table_name='follows')
    op.drop_index(op.f('ix_follows_target_id'), table_name='follows')
    op.drop_index(op.f('ix_follows_id'), table_name='follows')
    op.drop_index(op.f('ix_follows_follower_id'), table_name='follows')
    op.drop_index(op.f('ix_follows_created_at'), table_name='follows')
    op.drop_table('follows')
    # ### end Alembic commands ###
