import type { FeedItem } from './feedTypes';

export const mockFeedItems: FeedItem[] = [
  {
    id: 'pin-1',
    type: 'pin',
    pinType: 'memory_trick',
    course: 'Operating Systems',
    courseId: 'operating-systems',
    topic: 'CPU Scheduling',
    anchorText: 'Round Robin scheduling assigns a fixed time quantum to each process in a cyclic manner.',
    content:
      'Think of Round Robin like a relay race — each runner (process) gets exactly the same amount of time on the track before handing the baton to the next. No one can hog the track.',
    author: { id: 'u1', name: 'Mahlet A.', initials: 'MA', department: 'Computer Science' },
    postedAt: '2 hours ago',
    likes: 28,
    liked: false,
    saved: false,
    recommendation: 'recommended_from_course',
    documentId: 'doc-os-notes',
    sectionId: 'sec-cpu-scheduling',
  },
  {
    id: 'q-1',
    type: 'question',
    course: 'Operating Systems',
    courseId: 'operating-systems',
    topic: 'CPU Scheduling',
    anchorText: 'FCFS schedules processes in the order they arrive in the ready queue.',
    content: 'Why is FCFS considered unfair for shorter processes? Can it cause starvation?',
    author: { id: 'u2', name: 'Dawit M.', initials: 'DM', department: 'Software Engineering' },
    postedAt: '3 hours ago',
    likes: 18,
    liked: false,
    saved: false,
    replyCount: 12,
    replies: [
      {
        id: 'r1',
        author: { id: 'u3', name: 'Sara T.', initials: 'ST' },
        content:
          'FCFS suffers from the convoy effect — a long process blocks all shorter ones behind it. Shorter processes end up waiting disproportionately long, which is unfair but technically not starvation since they do eventually run.',
        likes: 9,
        createdAt: '2h ago',
        replies: [],
      },
      {
        id: 'r2',
        author: { id: 'u4', name: 'Yonas K.', initials: 'YK' },
        content:
          'Agreed. Starvation requires a process to wait indefinitely. In FCFS every process eventually gets the CPU, so there is no starvation — just poor average waiting time.',
        likes: 6,
        createdAt: '1h ago',
        replies: [],
      },
    ],
    recommendation: 'same_topic',
    documentId: 'doc-os-notes',
    sectionId: 'sec-cpu-scheduling',
  },
  {
    id: 'pin-2',
    type: 'pin',
    pinType: 'exam_hint',
    course: 'Operating Systems',
    courseId: 'operating-systems',
    topic: 'Memory Management',
    anchorText: 'Page replacement algorithms decide which page to evict when a page fault occurs.',
    content:
      'For the exit exam: LRU is almost always the best answer for "optimal in practice" but is expensive. OPT is theoretical optimal. FIFO suffers Belady\'s anomaly. Memorise these distinctions — they appear every year.',
    author: { id: 'u5', name: 'Hana G.', initials: 'HG', department: 'Computer Science' },
    postedAt: '5 hours ago',
    likes: 47,
    liked: false,
    saved: false,
    recommendation: 'popular_this_week',
    documentId: 'doc-os-notes',
    sectionId: 'sec-memory-management',
  },
  {
    id: 'q-2',
    type: 'question',
    course: 'Database Systems',
    courseId: 'database-systems',
    topic: 'Normalisation',
    anchorText: 'A relation is in 3NF if it is in 2NF and no non-prime attribute transitively depends on the primary key.',
    content: 'What is the practical difference between 3NF and BCNF? When would you prefer 3NF over BCNF?',
    author: { id: 'u6', name: 'Liya B.', initials: 'LB', department: 'Information Systems' },
    postedAt: 'Yesterday',
    likes: 14,
    liked: false,
    saved: false,
    replyCount: 7,
    replies: [
      {
        id: 'r3',
        author: { id: 'u3', name: 'Sara T.', initials: 'ST' },
        content:
          'BCNF is stricter — it eliminates more redundancy but can destroy lossless join and dependency preservation. 3NF is the sweet spot: it always allows a lossless-join decomposition that preserves dependencies.',
        likes: 11,
        createdAt: 'Yesterday',
        replies: [],
      },
    ],
    recommendation: 'from_someone_you_follow',
    documentId: 'doc-db-notes',
    sectionId: 'sec-normalisation',
  },
  {
    id: 'pin-3',
    type: 'pin',
    pinType: 'explanation',
    course: 'Computer Networks',
    courseId: 'computer-networks',
    topic: 'TCP/IP',
    anchorText: 'TCP provides reliable, ordered delivery through acknowledgements and retransmissions.',
    content:
      'TCP is like certified mail — you get a receipt for every letter. UDP is like dropping postcards in a box: fast, no receipt, occasional loss. Choose TCP when correctness matters; UDP when speed matters.',
    author: { id: 'u7', name: 'Abel F.', initials: 'AF', department: 'Network Engineering' },
    postedAt: '2 days ago',
    likes: 33,
    liked: false,
    saved: false,
    recommendation: 'popular_this_week',
    documentId: 'doc-networks-notes',
    sectionId: 'sec-tcp-ip',
  },
  {
    id: 'pin-4',
    type: 'pin',
    pinType: 'warning',
    course: 'Operating Systems',
    courseId: 'operating-systems',
    topic: 'Deadlock',
    anchorText: 'The four necessary conditions for deadlock are mutual exclusion, hold and wait, no preemption, and circular wait.',
    content:
      '⚠️ Students often confuse "deadlock prevention" with "deadlock avoidance". Prevention eliminates one of the four conditions statically. Avoidance (e.g. Banker\'s Algorithm) checks dynamically at runtime. The exam distinguishes these.',
    author: { id: 'u1', name: 'Mahlet A.', initials: 'MA', department: 'Computer Science' },
    postedAt: '3 days ago',
    likes: 62,
    liked: false,
    saved: false,
    recommendation: 'recommended_from_course',
    documentId: 'doc-os-notes',
    sectionId: 'sec-deadlock',
  },
  {
    id: 'q-3',
    type: 'question',
    course: 'Data Structures',
    courseId: 'data-structures',
    topic: 'Trees',
    anchorText: 'A balanced BST ensures O(log n) time for search, insert, and delete.',
    content:
      'What is the difference between an AVL tree and a Red-Black tree? Which performs better in practice and why?',
    author: { id: 'u8', name: 'Naol R.', initials: 'NR', department: 'Computer Science' },
    postedAt: '4 days ago',
    likes: 21,
    liked: false,
    saved: false,
    replyCount: 5,
    replies: [
      {
        id: 'r4',
        author: { id: 'u5', name: 'Hana G.', initials: 'HG' },
        content:
          'AVL trees are more strictly balanced so lookups are faster. Red-Black trees allow more relaxed balance so insertions and deletions are faster. In practice, Red-Black (used in std::map, Java TreeMap) wins for general use.',
        likes: 15,
        createdAt: '4 days ago',
        replies: [],
      },
    ],
    recommendation: 'same_topic',
    documentId: 'doc-ds-notes',
    sectionId: 'sec-trees',
  },
];
